### ISSUE TITLE
Create a top level CRM toolbar item

### ISSUE THREAD

**Issue by mirodietiker** [md-systems/crm_core#33]
Similar to TMGMT we want to build a menu link structure to maintain the default CRM UI.

All UI elements will be switched to the admin UI by default.
Below the CRM item, we can create a hierarchical menu structure with direct access from the toolbar. The lower levels are only accessible if the toolbar is on the left side, not on top.

**Comment by edurenye** [comment]
I created the pull request for it [#34](https://github.com/md-systems/crm_core/pull/34)

**Comment by arildm** [comment]
Merged
